spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
